import { useMemo, useState } from 'react';
import { UserPlus, MessageSquare, GraduationCap, Share2, type LucideIcon } from 'lucide-react';
import GreetingBanner from './GreetingBanner';
import DateRangeFilter from './DateRangeFilter';
import { ApplicationRecord, CounselorStudent, IntakeStudent } from '../types';
import {
  PLATFORM_SOURCES, platformBadgeStyle, isMarketingLead, parseLeadDate,
  leadBranch, consultationFor, applicationFor, QUALITY_STATUSES,
} from '../marketing';

interface MarketingOverviewProps {
  students: IntakeStudent[];
  counselorStudents: CounselorStudent[];
  applications: ApplicationRecord[];
}

type RangeKey = 'today' | '7d' | '30d' | 'custom';

const RANGE_OPTIONS: { key: RangeKey; label: string }[] = [
  { key: 'today', label: 'Today' },
  { key: '7d', label: '7 Days' },
  { key: '30d', label: '30 Days' },
  { key: 'custom', label: 'Custom' },
];

const ALL_PLATFORMS = 'All Platforms';

function dayStart(d: Date): Date {
  const copy = new Date(d.getTime());
  copy.setHours(0, 0, 0, 0);
  return copy;
}

export default function MarketingOverview({ students, counselorStudents, applications }: MarketingOverviewProps) {
  const [range, setRange] = useState<RangeKey>('30d');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [platform, setPlatform] = useState<string>(ALL_PLATFORMS);

  const marketingLeads = useMemo(() => students.filter(isMarketingLead), [students]);

  // Anchor "now" on the newest lead so the seeded demo data still lands inside the windows.
  const now = useMemo(() => {
    const dates = marketingLeads.map((l) => parseLeadDate(l.submittedAt)).filter((d): d is Date => d !== null);
    if (dates.length === 0) return new Date();
    return dates.reduce((latest, d) => (d > latest ? d : latest), dates[0]);
  }, [marketingLeads]);

  const filtered = useMemo(() => {
    return marketingLeads.filter((lead) => {
      if (platform !== ALL_PLATFORMS && lead.platformSource !== platform) return false;
      const date = parseLeadDate(lead.submittedAt);
      if (range === 'custom') {
        if (!from && !to) return true;
        if (!date) return false;
        const key = date.toISOString().slice(0, 10);
        if (from && key < from) return false;
        if (to && key > to) return false;
        return true;
      }
      if (!date) return false;
      if (range === 'today') return date >= dayStart(now);
      const days = range === '7d' ? 7 : 30;
      const start = new Date(now.getTime());
      start.setDate(start.getDate() - days);
      return date >= start;
    });
  }, [marketingLeads, platform, range, from, to, now]);

  const stats = useMemo<{ key: string; icon: LucideIcon; label: string; value: number; hint: string }[]>(() => {
    const quality = filtered.filter((lead) => {
      const consult = consultationFor(lead, counselorStudents);
      return consult ? QUALITY_STATUSES.includes(consult.consultationStatus) : false;
    }).length;
    const enrolled = filtered.filter((lead) => Boolean(applicationFor(consultationFor(lead, counselorStudents), applications))).length;
    const rate = filtered.length > 0 ? Math.round((quality / filtered.length) * 100) : 0;
    return [
      { key: 'leads', icon: UserPlus, label: 'Total New Leads', value: filtered.length, hint: 'Generated by Marketing' },
      { key: 'quality', icon: MessageSquare, label: 'Leads Converted to Consultation', value: quality, hint: `${rate}% quality rate` },
      { key: 'enrolled', icon: GraduationCap, label: 'Total Enrolled', value: enrolled, hint: 'Moved into the pipeline' },
    ];
  }, [filtered, counselorStudents, applications]);

  const byPlatform = useMemo(() => {
    const counts = PLATFORM_SOURCES.map((source) => ({
      source,
      count: filtered.filter((lead) => lead.platformSource === source).length,
    }));
    const extra = filtered.filter((lead) => lead.platformSource && !PLATFORM_SOURCES.includes(lead.platformSource));
    const grouped = new Map<string, number>();
    extra.forEach((lead) => grouped.set(lead.platformSource!, (grouped.get(lead.platformSource!) ?? 0) + 1));
    const rows = [...counts, ...[...grouped].map(([source, count]) => ({ source, count }))].filter((r) => r.count > 0);
    const max = rows.reduce((m, r) => Math.max(m, r.count), 0);
    return { rows: rows.sort((a, b) => b.count - a.count), max };
  }, [filtered]);

  const byBranch = useMemo(() => {
    const names = [...new Set(filtered.map(leadBranch))].sort();
    return names.map((name) => {
      const leads = filtered.filter((lead) => leadBranch(lead) === name);
      const consultations = leads.filter((lead) => {
        const consult = consultationFor(lead, counselorStudents);
        return consult ? QUALITY_STATUSES.includes(consult.consultationStatus) : false;
      }).length;
      const enrolled = leads.filter((lead) => Boolean(applicationFor(consultationFor(lead, counselorStudents), applications))).length;
      return {
        name,
        leads: leads.length,
        consultations,
        enrolled,
        rate: leads.length > 0 ? Math.round((consultations / leads.length) * 100) : 0,
      };
    });
  }, [filtered, counselorStudents, applications]);

  return (
    <div className="space-y-6">
      <GreetingBanner />

      {/* Global filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="inline-flex flex-wrap gap-1 rounded-xl border border-grey-border bg-white p-1">
          {RANGE_OPTIONS.map((opt) => {
            const active = opt.key === range;
            return (
              <button
                key={opt.key}
                type="button"
                aria-pressed={active}
                onClick={() => setRange(opt.key)}
                className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                  active ? 'bg-navy text-white' : 'text-gray-500 hover:bg-navy/5 hover:text-navy'
                }`}
              >
                {opt.label}
              </button>
            );
          })}
        </div>

        {range === 'custom' && (
          <DateRangeFilter from={from} to={to} onFromChange={setFrom} onToChange={setTo} />
        )}

        <div className="relative">
          <Share2 className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={15} />
          <select
            aria-label="Platform source"
            value={platform}
            onChange={(e) => setPlatform(e.target.value)}
            className="appearance-none rounded-lg border border-grey-border bg-white py-2 pl-9 pr-8 text-sm text-navy focus:border-navy-light focus:outline-none focus:ring-1 focus:ring-navy-light"
          >
            <option value={ALL_PLATFORMS}>{ALL_PLATFORMS}</option>
            {PLATFORM_SOURCES.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <div key={stat.key} className="rounded-2xl border border-grey-border bg-white p-5">
              <div className="mb-3 flex items-center justify-between">
                <span className="rounded-lg bg-navy/5 p-2 text-navy"><Icon size={18} /></span>
              </div>
              <p className="text-2xl font-semibold text-navy">{stat.value}</p>
              <p className="mt-1 text-sm font-medium text-navy">{stat.label}</p>
              <p className="text-xs text-gray-400">{stat.hint}</p>
            </div>
          );
        })}
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {/* Lead volume by platform */}
        <div className="rounded-2xl border border-grey-border bg-white p-5">
          <h3 className="mb-4 text-sm font-semibold text-navy">Lead Volume by Platform</h3>
          {byPlatform.rows.length === 0 ? (
            <p className="py-8 text-center text-sm text-gray-400">No leads in this period.</p>
          ) : (
            <div className="space-y-3">
              {byPlatform.rows.map((row) => (
                <div key={row.source}>
                  <div className="mb-1 flex items-center justify-between text-xs">
                    <span className={`rounded-full px-2.5 py-1 font-medium ${platformBadgeStyle(row.source)}`}>{row.source}</span>
                    <span className="font-semibold text-navy">{row.count}</span>
                  </div>
                  <div className="h-2 w-full overflow-hidden rounded-full bg-grey-bg">
                    <div
                      className="h-full rounded-full bg-navy transition-all"
                      style={{ width: `${byPlatform.max > 0 ? (row.count / byPlatform.max) * 100 : 0}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Conversion by branch */}
        <div className="overflow-hidden rounded-2xl border border-grey-border bg-white">
          <h3 className="border-b border-grey-border px-5 py-4 text-sm font-semibold text-navy">Conversion Rate by Branch</h3>
          {byBranch.length === 0 ? (
            <p className="py-8 text-center text-sm text-gray-400">No leads in this period.</p>
          ) : (
            <table className="w-full">
              <thead>
                <tr className="border-b border-grey-border bg-grey-bg">
                  <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500">Branch</th>
                  <th className="px-3 py-3 text-right text-xs font-semibold text-gray-500">Leads</th>
                  <th className="px-3 py-3 text-right text-xs font-semibold text-gray-500">Consultations</th>
                  <th className="px-3 py-3 text-right text-xs font-semibold text-gray-500">Enrolled</th>
                  <th className="px-5 py-3 text-right text-xs font-semibold text-gray-500">Conversion</th>
                </tr>
              </thead>
              <tbody>
                {byBranch.map((row) => (
                  <tr key={row.name} className="border-b border-grey-border last:border-0">
                    <td className="px-5 py-3 text-sm font-medium text-navy">{row.name}</td>
                    <td className="px-3 py-3 text-right text-sm text-gray-600">{row.leads}</td>
                    <td className="px-3 py-3 text-right text-sm text-gray-600">{row.consultations}</td>
                    <td className="px-3 py-3 text-right text-sm text-gray-600">{row.enrolled}</td>
                    <td className="px-5 py-3 text-right">
                      <span className="rounded-full bg-navy/10 px-2.5 py-1 text-xs font-medium text-navy">{row.rate}%</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}
