-- ============================================================================
-- RLS performance fix — every policy in 2026-09-27-rls-lockdown.sql calls
-- helper functions (is_super_admin(), same_branch(branch), current_role(),
-- ...) directly in USING/WITH CHECK. None of those calls are wrapped in a
-- `select`, so Postgres cannot hoist them into a one-time InitPlan — it
-- re-invokes them, and the `staff` table lookup inside current_staff() they
-- all funnel through, ONCE PER ROW of every table scanned. That's the classic
-- Supabase RLS performance trap (their linter's `auth_rls_initplan` warning)
-- and it's why fetching a table got much slower once real RLS replaced the
-- old `using (true)` policies — most visibly right after login, when
-- src/App.tsx fires ~40 table fetches at once.
--
-- Fix: wrap every helper-function call in `(select ...)` so Postgres treats
-- it as an uncorrelated subquery — computed once per query, cached, and
-- reused for every row — instead of a per-row function call. `same_branch(x)`
-- calls are inlined as `x is not null and x = (select current_branch())`,
-- which is exactly what same_branch()'s own body does, so this changes
-- nothing about who can see or write what — only how many times the
-- underlying staff lookup runs. Generated by mechanically re-wrapping every
-- policy from the lockdown migration; each one is otherwise byte-for-byte
-- the same boolean expression.
--
-- Safe to re-run: same drop-then-create pattern as the lockdown migration.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 2. Identity tables: staff, branches, counselors
-- ----------------------------------------------------------------------------

alter table public.staff enable row level security;

drop policy if exists staff_select on public.staff;
create policy staff_select on public.staff for select
using (
  (select public.is_super_admin())
  or auth_user_id = (select auth.uid())
  or (select public.is_marketing())
  or (branch is not null and branch = (select public.current_branch()))
);

drop policy if exists staff_insert on public.staff;
create policy staff_insert on public.staff for insert
with check (
  (select public.is_super_admin())
  or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch())) and role <> 'Super Admin')
);

drop policy if exists staff_update on public.staff;
create policy staff_update on public.staff for update
using (
  (select public.is_super_admin())
  or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch())))
)
with check (
  (select public.is_super_admin())
  or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch())) and role <> 'Super Admin')
);

drop policy if exists staff_delete on public.staff;
create policy staff_delete on public.staff for delete
using (
  (select public.is_super_admin())
  or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch())) and role <> 'Super Admin')
);

alter table public.branches enable row level security;

drop policy if exists branches_select on public.branches;
create policy branches_select on public.branches for select using ((select public.is_active_staff()));

drop policy if exists branches_insert on public.branches;
create policy branches_insert on public.branches for insert with check ((select public.is_super_admin()));

drop policy if exists branches_update on public.branches;
create policy branches_update on public.branches for update using ((select public.is_super_admin())) with check ((select public.is_super_admin()));

drop policy if exists branches_delete on public.branches;
create policy branches_delete on public.branches for delete using ((select public.is_super_admin()));

alter table public.counselors enable row level security;

drop policy if exists counselors_select on public.counselors;
create policy counselors_select on public.counselors for select using ((select public.is_active_staff()));

drop policy if exists counselors_insert on public.counselors;
create policy counselors_insert on public.counselors for insert with check ((select public.is_super_admin()) or (select public.is_branch_manager()));

drop policy if exists counselors_update on public.counselors;
create policy counselors_update on public.counselors for update
using ((select public.is_super_admin()) or (select public.is_branch_manager()))
with check ((select public.is_super_admin()) or (select public.is_branch_manager()));

drop policy if exists counselors_delete on public.counselors;
create policy counselors_delete on public.counselors for delete using ((select public.is_super_admin()) or (select public.is_branch_manager()));


-- ----------------------------------------------------------------------------
-- 3. Client pipeline: students, counselor_students, applications,
--    notifications, communication_logs, branch_transfers
-- ----------------------------------------------------------------------------

alter table public.students enable row level security;

drop policy if exists students_select on public.students;
create policy students_select on public.students for select
using ((select public.is_super_admin()) or ((branch is not null and branch = (select public.current_branch())) and not (select public.is_marketing())));

drop policy if exists students_insert on public.students;
create policy students_insert on public.students for insert
with check ((select public.is_super_admin()) or ((branch is not null and branch = (select public.current_branch())) and not (select public.is_marketing())));

drop policy if exists students_update on public.students;
create policy students_update on public.students for update
using ((select public.is_super_admin()) or ((branch is not null and branch = (select public.current_branch())) and not (select public.is_marketing())))
with check ((select public.is_super_admin()) or ((branch is not null and branch = (select public.current_branch())) and not (select public.is_marketing())));

drop policy if exists students_delete on public.students;
create policy students_delete on public.students for delete
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.counselor_students enable row level security;

drop policy if exists counselor_students_select on public.counselor_students;
create policy counselor_students_select on public.counselor_students for select
using (
  (select public.is_super_admin())
  or assigned_counselor = (select public.current_staff_name())
  or (
    not (select public.is_marketing())
    and exists (
      select 1 from public.staff s
      where s.name = counselor_students.assigned_counselor
        and (s.branch is not null and s.branch = (select public.current_branch()))
    )
  )
);

drop policy if exists counselor_students_insert on public.counselor_students;
create policy counselor_students_insert on public.counselor_students for insert
with check (
  (select public.is_super_admin())
  or assigned_counselor = (select public.current_staff_name())
  or (
    not (select public.is_marketing())
    and exists (
      select 1 from public.staff s
      where s.name = counselor_students.assigned_counselor
        and (s.branch is not null and s.branch = (select public.current_branch()))
    )
  )
);

drop policy if exists counselor_students_update on public.counselor_students;
create policy counselor_students_update on public.counselor_students for update
using (
  (select public.is_super_admin())
  or assigned_counselor = (select public.current_staff_name())
  or (
    not (select public.is_marketing())
    and exists (
      select 1 from public.staff s
      where s.name = counselor_students.assigned_counselor
        and (s.branch is not null and s.branch = (select public.current_branch()))
    )
  )
)
with check (
  (select public.is_super_admin())
  or assigned_counselor = (select public.current_staff_name())
  or (
    not (select public.is_marketing())
    and exists (
      select 1 from public.staff s
      where s.name = counselor_students.assigned_counselor
        and (s.branch is not null and s.branch = (select public.current_branch()))
    )
  )
);

drop policy if exists counselor_students_delete on public.counselor_students;
create policy counselor_students_delete on public.counselor_students for delete
using (
  (select public.is_super_admin())
  or (
    (select public.is_branch_manager())
    and exists (
      select 1 from public.staff s
      where s.name = counselor_students.assigned_counselor
        and (s.branch is not null and s.branch = (select public.current_branch()))
    )
  )
);

alter table public.applications enable row level security;

drop policy if exists applications_select on public.applications;
create policy applications_select on public.applications for select
using (
  (select public.is_super_admin())
  or ((branch is not null and branch = (select public.current_branch())) and ((select public.is_branch_manager()) or (select public.is_receptionist()) or (select public.is_application_officer())))
  or ((select public.is_counselor()) and counselor = (select public.current_staff_name()) and (branch is not null and branch = (select public.current_branch())))
);

drop policy if exists applications_insert on public.applications;
create policy applications_insert on public.applications for insert
with check (
  (select public.is_super_admin())
  or ((branch is not null and branch = (select public.current_branch())) and ((select public.is_branch_manager()) or (select public.is_receptionist()) or (select public.is_application_officer())))
  or ((select public.is_counselor()) and counselor = (select public.current_staff_name()) and (branch is not null and branch = (select public.current_branch())))
);

drop policy if exists applications_update on public.applications;
create policy applications_update on public.applications for update
using (
  (select public.is_super_admin())
  or ((branch is not null and branch = (select public.current_branch())) and ((select public.is_branch_manager()) or (select public.is_receptionist()) or (select public.is_application_officer())))
  or ((select public.is_counselor()) and counselor = (select public.current_staff_name()) and (branch is not null and branch = (select public.current_branch())))
)
with check (
  (select public.is_super_admin())
  or ((branch is not null and branch = (select public.current_branch())) and ((select public.is_branch_manager()) or (select public.is_receptionist()) or (select public.is_application_officer())))
  or ((select public.is_counselor()) and counselor = (select public.current_staff_name()) and (branch is not null and branch = (select public.current_branch())))
);

drop policy if exists applications_delete on public.applications;
create policy applications_delete on public.applications for delete
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.notifications enable row level security;

drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications for select
using (
  (select public.is_super_admin())
  or (
    role = (select public.current_role())
    and (
      (recipient_name is not null and recipient_name = (select public.current_staff_name()))
      or (recipient_name is null and (branch is null or (branch is not null and branch = (select public.current_branch()))))
    )
  )
);

drop policy if exists notifications_insert on public.notifications;
create policy notifications_insert on public.notifications for insert with check ((select public.is_active_staff()));

drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update
using (
  (select public.is_super_admin())
  or (
    role = (select public.current_role())
    and (
      (recipient_name is not null and recipient_name = (select public.current_staff_name()))
      or (recipient_name is null and (branch is null or (branch is not null and branch = (select public.current_branch()))))
    )
  )
)
with check (
  (select public.is_super_admin())
  or (
    role = (select public.current_role())
    and (
      (recipient_name is not null and recipient_name = (select public.current_staff_name()))
      or (recipient_name is null and (branch is null or (branch is not null and branch = (select public.current_branch()))))
    )
  )
);

drop policy if exists notifications_delete on public.notifications;
create policy notifications_delete on public.notifications for delete
using (
  (select public.is_super_admin())
  or (
    role = (select public.current_role())
    and (
      (recipient_name is not null and recipient_name = (select public.current_staff_name()))
      or (recipient_name is null and (branch is null or (branch is not null and branch = (select public.current_branch()))))
    )
  )
);

alter table public.communication_logs enable row level security;

drop policy if exists communication_logs_select on public.communication_logs;
create policy communication_logs_select on public.communication_logs for select using ((select public.is_active_staff()));

drop policy if exists communication_logs_insert on public.communication_logs;
create policy communication_logs_insert on public.communication_logs for insert with check ((select public.is_active_staff()));

alter table public.branch_transfers enable row level security;

drop policy if exists branch_transfers_select on public.branch_transfers;
create policy branch_transfers_select on public.branch_transfers for select
using ((select public.is_super_admin()) or (select public.current_branch()) in (from_branch, to_branch));

drop policy if exists branch_transfers_insert on public.branch_transfers;
create policy branch_transfers_insert on public.branch_transfers for insert
with check ((select public.is_super_admin()) or (to_branch is not null and to_branch = (select public.current_branch())));

drop policy if exists branch_transfers_update on public.branch_transfers;
create policy branch_transfers_update on public.branch_transfers for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (from_branch is not null and from_branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (from_branch is not null and from_branch = (select public.current_branch()))));


-- ----------------------------------------------------------------------------
-- 4. Finance: fin_transactions, expense_requests, service_prices,
--    commissions, partners
-- ----------------------------------------------------------------------------

alter table public.fin_transactions enable row level security;

drop policy if exists fin_transactions_select on public.fin_transactions;
create policy fin_transactions_select on public.fin_transactions for select
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists fin_transactions_insert on public.fin_transactions;
create policy fin_transactions_insert on public.fin_transactions for insert
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists fin_transactions_update on public.fin_transactions;
create policy fin_transactions_update on public.fin_transactions for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.expense_requests enable row level security;

drop policy if exists expense_requests_select on public.expense_requests;
create policy expense_requests_select on public.expense_requests for select
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists expense_requests_insert on public.expense_requests;
create policy expense_requests_insert on public.expense_requests for insert
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists expense_requests_update on public.expense_requests;
create policy expense_requests_update on public.expense_requests for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.service_prices enable row level security;

drop policy if exists service_prices_select on public.service_prices;
create policy service_prices_select on public.service_prices for select using ((select public.is_active_staff()));

drop policy if exists service_prices_insert on public.service_prices;
create policy service_prices_insert on public.service_prices for insert with check ((select public.is_super_admin()));

alter table public.commissions enable row level security;

drop policy if exists commissions_select on public.commissions;
create policy commissions_select on public.commissions for select
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists commissions_update on public.commissions;
create policy commissions_update on public.commissions for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.partners enable row level security;

drop policy if exists partners_select on public.partners;
create policy partners_select on public.partners for select using ((select public.is_active_staff()));

drop policy if exists partners_insert on public.partners;
create policy partners_insert on public.partners for insert with check ((select public.is_super_admin()));

drop policy if exists partners_update on public.partners;
create policy partners_update on public.partners for update using ((select public.is_super_admin())) with check ((select public.is_super_admin()));

drop policy if exists partners_delete on public.partners;
create policy partners_delete on public.partners for delete using ((select public.is_super_admin()));


-- ----------------------------------------------------------------------------
-- 5. HR
-- ----------------------------------------------------------------------------

alter table public.attendance enable row level security;

drop policy if exists attendance_select on public.attendance;
create policy attendance_select on public.attendance for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists attendance_insert on public.attendance;
create policy attendance_insert on public.attendance for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists attendance_update on public.attendance;
create policy attendance_update on public.attendance for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

alter table public.attendance_corrections enable row level security;

drop policy if exists attendance_corrections_select on public.attendance_corrections;
create policy attendance_corrections_select on public.attendance_corrections for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists attendance_corrections_insert on public.attendance_corrections;
create policy attendance_corrections_insert on public.attendance_corrections for insert
with check ((select public.is_super_admin()) or staff_name = (select public.current_staff_name()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists attendance_corrections_update on public.attendance_corrections;
create policy attendance_corrections_update on public.attendance_corrections for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.attendance_explanations enable row level security;

drop policy if exists attendance_explanations_select on public.attendance_explanations;
create policy attendance_explanations_select on public.attendance_explanations for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists attendance_explanations_insert on public.attendance_explanations;
create policy attendance_explanations_insert on public.attendance_explanations for insert
with check ((select public.is_super_admin()) or staff_name = (select public.current_staff_name()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists attendance_explanations_update on public.attendance_explanations;
create policy attendance_explanations_update on public.attendance_explanations for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

alter table public.holidays enable row level security;

drop policy if exists holidays_select on public.holidays;
create policy holidays_select on public.holidays for select using ((select public.is_active_staff()));

drop policy if exists holidays_insert on public.holidays;
create policy holidays_insert on public.holidays for insert with check ((select public.is_super_admin()) or (select public.is_branch_manager()));

drop policy if exists holidays_update on public.holidays;
create policy holidays_update on public.holidays for update
using ((select public.is_super_admin()) or (select public.is_branch_manager()))
with check ((select public.is_super_admin()) or (select public.is_branch_manager()));

drop policy if exists holidays_delete on public.holidays;
create policy holidays_delete on public.holidays for delete using ((select public.is_super_admin()) or (select public.is_branch_manager()));

alter table public.leave_records enable row level security;

drop policy if exists leave_records_select on public.leave_records;
create policy leave_records_select on public.leave_records for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists leave_records_insert on public.leave_records;
create policy leave_records_insert on public.leave_records for insert
with check ((select public.is_super_admin()) or staff_name = (select public.current_staff_name()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists leave_records_update on public.leave_records;
create policy leave_records_update on public.leave_records for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.pay_profiles enable row level security;

drop policy if exists pay_profiles_select on public.pay_profiles;
create policy pay_profiles_select on public.pay_profiles for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists pay_profiles_insert on public.pay_profiles;
create policy pay_profiles_insert on public.pay_profiles for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists pay_profiles_update on public.pay_profiles;
create policy pay_profiles_update on public.pay_profiles for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.payroll_runs enable row level security;

drop policy if exists payroll_runs_select on public.payroll_runs;
create policy payroll_runs_select on public.payroll_runs for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists payroll_runs_insert on public.payroll_runs;
create policy payroll_runs_insert on public.payroll_runs for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists payroll_runs_update on public.payroll_runs;
create policy payroll_runs_update on public.payroll_runs for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.performance_reviews enable row level security;

drop policy if exists performance_reviews_select on public.performance_reviews;
create policy performance_reviews_select on public.performance_reviews for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

drop policy if exists performance_reviews_insert on public.performance_reviews;
create policy performance_reviews_insert on public.performance_reviews for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists performance_reviews_update on public.performance_reviews;
create policy performance_reviews_update on public.performance_reviews for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or staff_name = (select public.current_staff_name()));

alter table public.onboarding_cases enable row level security;

drop policy if exists onboarding_cases_select on public.onboarding_cases;
create policy onboarding_cases_select on public.onboarding_cases for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists onboarding_cases_insert on public.onboarding_cases;
create policy onboarding_cases_insert on public.onboarding_cases for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists onboarding_cases_update on public.onboarding_cases;
create policy onboarding_cases_update on public.onboarding_cases for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.offboarding_cases enable row level security;

drop policy if exists offboarding_cases_select on public.offboarding_cases;
create policy offboarding_cases_select on public.offboarding_cases for select
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists offboarding_cases_insert on public.offboarding_cases;
create policy offboarding_cases_insert on public.offboarding_cases for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists offboarding_cases_update on public.offboarding_cases;
create policy offboarding_cases_update on public.offboarding_cases for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));


-- ----------------------------------------------------------------------------
-- 6. Ops: tasks, it_tickets, branch_notices, branch_issues,
--    branch_day_logs, branch_content_requests, marketing_support_requests
-- ----------------------------------------------------------------------------

alter table public.tasks enable row level security;

drop policy if exists tasks_select on public.tasks;
create policy tasks_select on public.tasks for select using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists tasks_insert on public.tasks;
create policy tasks_insert on public.tasks for insert with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists tasks_update on public.tasks;
create policy tasks_update on public.tasks for update
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())))
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists tasks_delete on public.tasks;
create policy tasks_delete on public.tasks for delete
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))) or created_by = (select public.current_staff_name()));

alter table public.it_tickets enable row level security;

drop policy if exists it_tickets_select on public.it_tickets;
create policy it_tickets_select on public.it_tickets for select using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists it_tickets_insert on public.it_tickets;
create policy it_tickets_insert on public.it_tickets for insert with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists it_tickets_update on public.it_tickets;
create policy it_tickets_update on public.it_tickets for update
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())))
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

alter table public.branch_notices enable row level security;

drop policy if exists branch_notices_select on public.branch_notices;
create policy branch_notices_select on public.branch_notices for select using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists branch_notices_insert on public.branch_notices;
create policy branch_notices_insert on public.branch_notices for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists branch_notices_update on public.branch_notices;
create policy branch_notices_update on public.branch_notices for update
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())))
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

alter table public.branch_issues enable row level security;

drop policy if exists branch_issues_select on public.branch_issues;
create policy branch_issues_select on public.branch_issues for select using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists branch_issues_insert on public.branch_issues;
create policy branch_issues_insert on public.branch_issues for insert with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists branch_issues_update on public.branch_issues;
create policy branch_issues_update on public.branch_issues for update
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())))
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

alter table public.branch_day_logs enable row level security;

drop policy if exists branch_day_logs_select on public.branch_day_logs;
create policy branch_day_logs_select on public.branch_day_logs for select using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists branch_day_logs_insert on public.branch_day_logs;
create policy branch_day_logs_insert on public.branch_day_logs for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists branch_day_logs_update on public.branch_day_logs;
create policy branch_day_logs_update on public.branch_day_logs for update
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))))
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.branch_content_requests enable row level security;

drop policy if exists branch_content_requests_select on public.branch_content_requests;
create policy branch_content_requests_select on public.branch_content_requests for select
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())) or (select public.is_marketing()));

drop policy if exists branch_content_requests_insert on public.branch_content_requests;
create policy branch_content_requests_insert on public.branch_content_requests for insert
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())));

drop policy if exists branch_content_requests_update on public.branch_content_requests;
create policy branch_content_requests_update on public.branch_content_requests for update
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())) or (select public.is_marketing()));

drop policy if exists branch_content_requests_delete on public.branch_content_requests;
create policy branch_content_requests_delete on public.branch_content_requests for delete
using ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

alter table public.marketing_support_requests enable row level security;

drop policy if exists marketing_support_requests_select on public.marketing_support_requests;
create policy marketing_support_requests_select on public.marketing_support_requests for select
using ((select public.is_super_admin()) or (branch is not null and branch = (select public.current_branch())) or (select public.is_marketing()));

drop policy if exists marketing_support_requests_insert on public.marketing_support_requests;
create policy marketing_support_requests_insert on public.marketing_support_requests for insert
with check ((select public.is_super_admin()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists marketing_support_requests_update on public.marketing_support_requests;
create policy marketing_support_requests_update on public.marketing_support_requests for update
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));


-- ----------------------------------------------------------------------------
-- 7. Marketing department
-- ----------------------------------------------------------------------------

alter table public.marketing_leads enable row level security;
drop policy if exists marketing_leads_all on public.marketing_leads;
create policy marketing_leads_all on public.marketing_leads for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_campaigns enable row level security;
drop policy if exists marketing_campaigns_all on public.marketing_campaigns;
create policy marketing_campaigns_all on public.marketing_campaigns for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_ad_spend enable row level security;
drop policy if exists marketing_ad_spend_all on public.marketing_ad_spend;
create policy marketing_ad_spend_all on public.marketing_ad_spend for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_content_requests enable row level security;

drop policy if exists marketing_content_requests_select on public.marketing_content_requests;
create policy marketing_content_requests_select on public.marketing_content_requests for select
using ((select public.is_super_admin()) or (select public.is_marketing()) or (target_branch is not null and target_branch = (select public.current_branch())));

drop policy if exists marketing_content_requests_insert on public.marketing_content_requests;
create policy marketing_content_requests_insert on public.marketing_content_requests for insert
with check ((select public.is_super_admin()) or (select public.is_marketing()));

drop policy if exists marketing_content_requests_update on public.marketing_content_requests;
create policy marketing_content_requests_update on public.marketing_content_requests for update
using ((select public.is_super_admin()) or (select public.is_marketing()) or (target_branch is not null and target_branch = (select public.current_branch())))
with check ((select public.is_super_admin()) or (select public.is_marketing()) or (target_branch is not null and target_branch = (select public.current_branch())));

drop policy if exists marketing_content_requests_delete on public.marketing_content_requests;
create policy marketing_content_requests_delete on public.marketing_content_requests for delete
using ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_content_items enable row level security;
drop policy if exists marketing_content_items_all on public.marketing_content_items;
create policy marketing_content_items_all on public.marketing_content_items for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_design_tasks enable row level security;
drop policy if exists marketing_design_tasks_all on public.marketing_design_tasks;
create policy marketing_design_tasks_all on public.marketing_design_tasks for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_video_tasks enable row level security;
drop policy if exists marketing_video_tasks_all on public.marketing_video_tasks;
create policy marketing_video_tasks_all on public.marketing_video_tasks for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_posts enable row level security;
drop policy if exists marketing_posts_all on public.marketing_posts;
create policy marketing_posts_all on public.marketing_posts for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_seo_tasks enable row level security;
drop policy if exists marketing_seo_tasks_all on public.marketing_seo_tasks;
create policy marketing_seo_tasks_all on public.marketing_seo_tasks for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_seo_keywords enable row level security;
drop policy if exists marketing_seo_keywords_all on public.marketing_seo_keywords;
create policy marketing_seo_keywords_all on public.marketing_seo_keywords for all
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

alter table public.marketing_pings enable row level security;

drop policy if exists marketing_pings_select on public.marketing_pings;
create policy marketing_pings_select on public.marketing_pings for select
using ((select public.is_super_admin()) or (select public.is_marketing()) or ((select public.is_branch_manager()) and (branch is not null and branch = (select public.current_branch()))));

drop policy if exists marketing_pings_insert on public.marketing_pings;
create policy marketing_pings_insert on public.marketing_pings for insert with check ((select public.is_super_admin()) or (select public.is_marketing()));

drop policy if exists marketing_pings_update on public.marketing_pings;
create policy marketing_pings_update on public.marketing_pings for update
using ((select public.is_super_admin()) or (select public.is_marketing()))
with check ((select public.is_super_admin()) or (select public.is_marketing()));

drop policy if exists marketing_pings_delete on public.marketing_pings;
create policy marketing_pings_delete on public.marketing_pings for delete using ((select public.is_super_admin()) or (select public.is_marketing()));


-- ----------------------------------------------------------------------------
-- 8. Audit log
-- ----------------------------------------------------------------------------

alter table public.audit_log enable row level security;

drop policy if exists audit_log_select on public.audit_log;
create policy audit_log_select on public.audit_log for select using ((select public.is_super_admin()));

drop policy if exists audit_log_insert on public.audit_log;
create policy audit_log_insert on public.audit_log for insert with check ((select public.is_active_staff()));
